services:
  nest-learning-db:
    image: "postgis/postgis:17-3.5"
    ports: 
      - "5434:5432"
    environment:
      - POSTGRES_USER=sjadmin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=jobber-auth
